import { createApp } from 'vue'
import { createPinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
import App from './App.vue'
import router from './router'
import './assets/global.css'

// ── FontAwesome ──────────────────────────────────────────────────────────
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { 
  // Solid Icons
  faChartBar,
  faBullhorn,
  faComments,
  faUser,
  faLock,
  faDoorOpen,
  faCreditCard,
  faRightFromBracket,
  faBars,
  faBuilding,
  faCheckCircle,
  faHouse,
  faMoneyBill,
  faXmark,
  faMobileAlt,
  faTrash,
  faFloppyDisk,
  faBan,
  faStar,
  faTriangleExclamation,
  faKey,
  faSpinner,
  faEnvelope,
  faEye,
  faInfoCircle,
  faTv,
  faFutbol,
  faTrophy,
  faCalendarAlt,
  faSearch,
  faSync,
  faFilm,
  faPlus,
  faPen,
  faTimes,
  faCalendar,
  faFolderOpen,
  faLink,
  faTowerBroadcast,
  faSeedling,
  faSatellite,
  faGlobeAfrica,
  faCloudUploadAlt,
  faBrain,
  faBullseye,
  faCogs,
  faCode,
  faTag,
  faUsers,
  faBriefcase,
  faClock,
  faChartLine,
  faPlug,
  faCloud,
  faPalette,
  faArrowRight,
  faRocket,
  faCheckCircle as faCheckCircleSolid,
  faCircleExclamation,
  faFolder,
  faFile,
  faEdit,
  faSave,
  faUndo,
  faRedo,
  faCopy,
  faPaste,
  faCut,
  faPrint,
  faDownload,
  faUpload,
  faShare,
  faHeart,
  faThumbsUp,
  faThumbsDown,
  faRotate,
  faReply,
  faPaperPlane,
  faSignInAlt,
  faUserPlus,
  faPhone,
  faLocationDot,
  faCog,
  faCoins,
  faEnvelope as faEnvelopeSolid,
  faRobot,
  faGamepad,
  faMusic,
  faCamera,
  faVideo,
  faHeadphones,
  faMicrophone,
  faDesktop,
  faLaptop,
  faTablet,
  faPrint as faPrintSolid,
  faArrowRightToBracket,
  faArrowLeft,
} from '@fortawesome/free-solid-svg-icons'

import { 
  faCalendar as faCalendarRegular,
  faEye as faEyeRegular,
  faEyeSlash as faEyeSlashRegular,
  faStar as faStarRegular,
  faComment,
  faEnvelope as faEnvelopeRegular,
  faUser as faUserRegular,
  faPaperPlane as faPaperPlaneRegular,
  faClock as faClockRegular,
  faCircle as faCircleRegular,
  faCircleCheck as faCircleCheckRegular,
} from '@fortawesome/free-regular-svg-icons'

import {
  faGithub,
  faTwitter,
  faLinkedin,
  faLinkedinIn,
  faFacebook,
  faFacebookF,
  faInstagram,
  faYoutube,
  faWhatsapp,
} from '@fortawesome/free-brands-svg-icons'

// Add all icons to the library
library.add(
  // Solid Icons
  faChartBar,
  faBullhorn,
  faComments,
  faUser,
  faLock,
  faDoorOpen,
  faCreditCard,
  faRightFromBracket,
  faBars,
  faBuilding,
  faCheckCircle,
  faHouse,
  faMoneyBill,
  faXmark,
  faMobileAlt,
  faTrash,
  faFloppyDisk,
  faBan,
  faStar,
  faTriangleExclamation,
  faKey,
  faSpinner,
  faEnvelope,
  faEye,
  faInfoCircle,
  faTv,
  faFutbol,
  faTrophy,
  faCalendarAlt,
  faSearch,
  faSync,
  faFilm,
  faPlus,
  faPen,
  faTimes,
  faCalendar,
  faFolderOpen,
  faLink,
  faTowerBroadcast,
  faSeedling,
  faSatellite,
  faGlobeAfrica,
  faCloudUploadAlt,
  faBrain,
  faBullseye,
  faCogs,
  faCode,
  faTag,
  faUsers,
  faBriefcase,
  faClock,
  faChartLine,
  faPlug,
  faCloud,
  faPalette,
  faArrowRight,
  faRocket,
  faCheckCircleSolid,
  faCircleExclamation,
  faFolder,
  faFile,
  faEdit,
  faSave,
  faUndo,
  faRedo,
  faCopy,
  faPaste,
  faCut,
  faPrintSolid,
  faDownload,
  faUpload,
  faShare,
  faHeart,
  faThumbsUp,
  faThumbsDown,
  faRotate,
  faReply,
  faPaperPlane,
  faSignInAlt,
  faUserPlus,
  faPhone,
  faLocationDot,
  faCog,
  faCoins,
  faEnvelopeSolid,
  faRobot,
  faGamepad,
  faMusic,
  faCamera,
  faVideo,
  faHeadphones,
  faMicrophone,
  faDesktop,
  faLaptop,
  faTablet,
  faArrowRightToBracket,
  faArrowLeft,
  
  // Regular Icons
  faCalendarRegular,
  faEyeRegular,
  faEyeSlashRegular,
  faStarRegular,
  faComment,
  faEnvelopeRegular,
  faUserRegular,
  faPaperPlaneRegular,
  faClockRegular,
  faCircleRegular,
  faCircleCheckRegular,
  
  // Brand Icons
  faGithub,
  faTwitter,
  faLinkedin,
  faLinkedinIn,
  faFacebook,
  faFacebookF,
  faInstagram,
  faYoutube,
  faWhatsapp,
)

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

const app = createApp(App)
app.component('font-awesome-icon', FontAwesomeIcon)
app.use(pinia)
app.use(router)
app.mount('#app')